/// Flutter icons Searchbar
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Searchbar
///      fonts:
///       - asset: fonts/Searchbar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Searchbar {
  Searchbar._();

  static const _kFontFam = 'Searchbar';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
